### ISSUE TITLE
Links are not coloured in messages

### ISSUE THREAD

**Issue by NusryNizam** [Fenimoure/Telegram-Adwaita-Dark-theme#3]
Only a mouse hover shows there's a link. It's not coloured or underlined.

![SS](https://user-images.githubusercontent.com/24385617/167875279-107dd909-c81c-4d2d-bd87-ba20f651e0e5.png)

**Comment by Fenimoure** [comment]
Hi! Thank you for your report. As far as I know both themes have this issue. I am already working on some fixes. It is  obvious the links have to be blueish, but the _msgOutBg_ is also blue so I don't know if I have to change _historyLinkOutFg_ to any blue-y color.

Here is how it looks in the incoming message:
![зображення](https://user-images.githubusercontent.com/68148186/167919877-1a5e3b67-335f-403d-9b40-1491ff65382f.png)


And here is how it looks in the outcoming message:
![зображення](https://user-images.githubusercontent.com/68148186/167919031-cb611377-274b-438f-ac33-f3460fda3b16.png)


P.S. Once again, as far as I know, no links in Telegram are underlined by default.
